### ISSUE TITLE
incoming call window

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#102]
Hi,

I know that when there's an incoming call you hear a ringer tone and a message in a window pops up if no buddy is selected or an HTML content shows up if the buddy is on-screen. 

However, what is the behavior supposed to be if another buddy is selected when there's an incoming call? I understand that in this case there's no pop-up window and that the only thing that happens is:

1) you hear the ringer tone

2) you are supposed to see some kind of reddish icon in the contact list to the left

Some users have reported that they could hear the ringer tone bit they could not see who was ringing on the left panel (they had another buddy selected). So it was frustrating for them because they knew they had an incoming call that they couldn't answer (notifications were not enabled at the time).

Could there be a "setItem" variable that one could set to "force" the incoming call window to show up *only* if the call's buddy contact is not selected?

**Comment by InnovateAsterisk** [comment]
Ill take a look at that, some things may have changed since the "lines" behaviour was introduced, but yes the concept is correct, if you are on a call, it will indicate an incoming call (using a softer ring - the call waiting indicator), and increment the red badge with the buddy calling (and make one if the buddy doesn't exist).

The idea is that it's quite distracting to have ring tones, and popups when you may already be on an important call. 

Would it not be better that a call gets made into a full blown "line" and listed with the lines (above buddies)?... this way it's very easy to see any new incoming calls while you have been on another call. Switching over to that line then presents you with the call answer / reject buttons.

**Comment by vieridipaola** [comment]
Yes, that would be fine.
The idea is that it should be quick and easy to just click and answer, especially when the buddy list can have 100+ contacts.
I don't remember if the "line" is always visible or if it scrolls up when the user goes down the buddy list.
Of course it would be better if it were always in a fixed position, separate from the buddy list scroll.
Thanks!

**Comment by InnovateAsterisk** [comment]
Agreed.

Yes, the Lines appear above all contacts.

**Comment by vieridipaola** [comment]
Line is on top of the contact/buddy list, but it seems to be within the scroll, so if the contact list is very long "Line" will not be visible unless the user scrolls up. "Line" would have to be a fixed area between the search box and the buddy list, IMHO.

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
