### ISSUE TITLE
Only allow incoming for buddy list

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#124]
Hi,

I have the following use case.

I want users to log into browser-phone, erase their buddy list, preload/provision a set of contacts (let's say, 30 patients, some with just one number, others with two), block all calls (as in DND) but only for those numbers that are not on the contact list. 

I can do all of the above, except for the last part. A cool new feature would be to add a toggable option in the drop-down menu, much like DND, that would be labeled something like "DND except contacts". Yet another cool feature would be another option labeled "DND except contacts & local". In the first case, the user would be able to call and receive calls from patients only (any other incoming call would be ignored and its contact details would not be added to the contact list, of course). In the second case, the user would also be able to receive calls from an admin-defined extension length (eg. in our organization, local extensions have a length of 4).

I might be able to program this in Asterisk instead (maybe with a feature code). However, I find it makes more sense to do this on the client as the buddy list is something that the user can quickly change in the browser and wouldn't necessarily have to be sent to the server.
 
I know there are more pressing tasks (like support for xmpp coming real soon, right? ;-) ), but any preliminary thoughts on this?

Thanks,

Vieri

**Comment by InnovateAsterisk** [comment]
Well, my immediate response is that this kind of call management could easily be done in the dial plan, an in fact may be a better place, if say the agent/doctor is on another channel of the extension (say his/her desk phone), or just busy on a call, then the call count could reveal a busy status. The question becomes what do you want to do with the call? If you bin the call, it could be rude... while you are still in the dial plan, you could send the caller to the voicemail service, or even put them in a holding queue, until the doctor is available again. Most of these options are easier while still in the dial plan. (That's not to say to cant get a "busy here" response, and handle the call after the Dial() function)

However, if you still want to handle this client side, in order to not add too much new code at this point, it would probably be best that a new web hook be set at the "web_hook_on_before_invite" stage. (Not web_hook_on_invite, as this would be too late.) There is a point that the call has entered the client, but no actions have taken place - this is before the invite handling code fires, and if there is a web hook there, you can handle all the privacy and screening in your own custom code.

For a quick win, just edit the main code, as it may be some time still for next release.

Find
```
    userAgent.on("invite", function (session) {
       ReceiveCall(session);

```
and change this to something like:

```
    userAgent.on("invite", function (session) {
       if(typeof web_hook_on_before_invite !== 'undefined') {
           if(web_hook_on_before_invite(session)) return;
        }
       ReceiveCall(session);

```
having the return in there, will mean that if the function returns true, it will stop the invite code going ahead, so make sure you handle the call properly.

**With regards to XMPP**, well... it hasn't been as easy as I imagined. The protocol is simple and easy to implement, it's just very old-school, and been years since anyone gave it any modern functionality, and while there is some movement, the features are almost all classified as "in development" and therefore the server software is all behind, as they will not implement too many features that are subject to change. The next release will have basic buddy management via XMPP using the roster, and vCard data for details like name and email etc, and profile pictures. The group activity however is main task right now... XMPP uses an IRC style "room" concept, where users "enter a room", chats a bit and then leaves... this was then turned around by Whatsapp, and now the more common concept is that you "create a group (or are joined to a group by an admin)", and from then on you receive what the group receives and it doesn't matter if you are online or not. Anyone, at any time, can hit a button and startup a video/audio session and if you can answer in time, you are in.... XMPP doesn't really have this, except for something called MIX - its apparently the same, but is lacking in some of the features... well this is currently where the R&D is for me. 

My aim is still to have the audio/video sessions establish via Asterisk/SIP (either as a direct call or via a conference), and the chat sessions via XMPP, so to marry the two is still the best of both worlds im after.

**Comment by vieridipaola** [comment]
Thanks for the suggestions.

Well, many software implementations try to marry both protocols SIP and XMPP. I have many clients still using an "old" customized version of Jitsi Desktop. This softphone uses the XMPP account just for chatting and sending files (1:1 or groups). All the rest (audio, video, conferences) is done with the SIP account.

**Comment by vieridipaola** [comment]
Regarding the original post, yes, I was thinking of handling the call after the Dial() function (busy here) in the dialplan.

Handling it "all" within the Asterisk dialplan and not the client makes me wonder how I'm supposed to know which calls are allowed and which are not.
The client (doctor) can add, delete, edit his/her contact list within browser-phone on the fly, and then simply enable an option, say, "DND except my list". If I wanted to do that in the dialplan then I guess I'd have to fetch that list of numbers somehow.
Doing it all client-side seems easier to me.

Of course, a rejected call is always handled somehow in the dialplan (either voicemail or message or transferred to someone else, etc.).

Anyway, your suggestions should put me on the right track. I won't bother you with suggested patches until you get a new release rolling out... :-)

Thanks!

**Comment by InnovateAsterisk** [comment]
What would you call this mode? 
"Private Mode"
"DND Private Mode"
"DND Contacts Only"

**Comment by vieridipaola** [comment]
I'd say "DND Contacts Only".

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128

It's a little different to what was initially described, but how it works is that a buddy can be set to "Allow calls during DND" in the contact details - then you simply put your self on DND, and only the buddies that you have said can call you (like say your boss etc) can call in. 

![image](https://user-images.githubusercontent.com/58937573/119307736-6e6c1900-bc6c-11eb-88f1-122a8326e806.png)
