### ISSUE TITLE
Client-side call recording

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#135]
Hi,

Client-side call recordings work fine with Google Chrome, but they fail with Firefox (88.0 ; 64-bit) with the following messages in its console:

```
setSinkId() is not possible using this browser. phone.js:5265:17

IndexDB CallRecordings.Recordings does not exists phone.js:5284:21

Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.
```

According to https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId#browser_compatibility, the user must explicitly enable the feature in order to use setSinkId().
How is that done?

My Browser-Phone web server issues this PHP command:

`header("Feature-Policy: camera *; microphone *;");`

Upon connection of a specific client without a webcam, the user accepts to enable the microphone, but the recordings fail to reproduce after a call.
 
So, why is the Firefox client failing? Is there another feature I should enable?

**Comment by InnovateAsterisk** [comment]
The ```setSinkId()``` is not related to the call recording, its a function of the audio element that is not supported (natively) by Firefox (for some odd reason). It's used to allow the user to control what output device is playing the audio stream. It's used extensively in this app but is tested for when called.

```
    if (typeof audioObj.sinkId !== 'undefined') {           <----
        audioObj.setSinkId(sinkId).then(function(){
            console.log("sinkId applied: "+ sinkId);
        }).catch(function(e){
            console.warn("Error using setSinkId: ", e);
        });
    } else {
        console.warn("setSinkId() is not possible using this browser.")
    }
```
The result is that a user is not able to use any other device other than the "default" audio output device. This setting can be seen as redundant since typically you have control over the playback device on any operating system using the built in system sound settings. However, what Firefox developers have failed to acknowledge is that there may be cases that a browser application may need to play one sound via one device, and another sound through another device... this project has this use case. The user may want the phone to ring on one device, and have the audio of the call on another - like a speaker and a headphone. Firefox cannot accommodate for this.

(I'm not sure how to explicitly enable this.)

With Regards to ```IndexDB CallRecordings.Recordings does not exists phone.js:5284:21```
In my tests, I was able to record audio correctly, and save it to the IndexDB CallRecordings.Recordings. The possible cause of the problem may be in the checking code. I suspect what happened to you was that the Database was created, but not the Table, so the code would assume that if the DB was there, so too was the Table.

What you may need to do is drop the Database, so the re-create code makes both the DB and the Table. BUT PLEASE CHECK FIRST.... it must look something like this, otherwise it was not create correctly:

![image](https://user-images.githubusercontent.com/58937573/116864963-03996600-ac09-11eb-9cd0-743c98b29bc7.png)

If you don't have both the CallRecordings (Database) and the Recordings (Table), then its wrong, and you must drop and re-create the CallRecordings Database.

![image](https://user-images.githubusercontent.com/58937573/116865074-3c393f80-ac09-11eb-93ff-4e40fc712914.png)

Here is Firefox saving the call recordings to the database.

The extra headers ```header("Feature-Policy: camera *; microphone *;");``` are only needed for IFRAMEs when an embedded page makes use of media devices when the two pages are not on the same domain. As you can see here:
https://www.innovateasterisk.com/phone/responsive.html
Both the pages are from the same site, so no such headers are necessary.

**Comment by vieridipaola** [comment]
Spot on. The Recordins tabel was not there. I deleted the CallRecordings DB, and the table was created. Now I can play the recorded files just fine.
Well, in this case I could do it manually on my computer, but would it be possible for phone.js to handle it automatically, ie. if the table doesn't exist anymore (for some odd reason), create it?

**Comment by InnovateAsterisk** [comment]
I'll also look at updating that code to do an additional test.

**Comment by InnovateAsterisk** [comment]
That's a bit annoying of Firefox, because the other players have the download link built into the HTML5 player, but they have to be fully loaded (as they actually stream from the IndexDB to the player). In Chrome you will see the 3 dots appear once the download indicator (the light grey bar you see behind the progress bar) reaches 100%.

In order to accommodate for this (and for if you really have a long recording), you open the call detail record, by clicking the little arrow for the menu, then select "Show Call Detail Record", in this page, the recording is directly downloadable - See the Call Recordings section (If there are multiple, all are listed). Depending on how your browsers is configured, it may try to play it in place, so rather right click and select save as.

(it is marked as downloadable, but you never know, so best to just Save As...)

**Comment by vieridipaola** [comment]
Got it. Thanks!

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
