### ISSUE TITLE
type numbers with keyboard in keypad

### ISSUE THREAD

**Issue by edimondi** [InnovateAsterisk/Browser-Phone#144]
hi, i was thinking if i can make when i click the call button i want to start typing right away with keyboard and when i press enter i want to make the audio call because is more easy than the mouse. thanks

**Comment by acoolov** [comment]
You can click on the invisible text field right above the keypad and start typing the number, but being able to just start typing the number right away would be way more convenient. The app definitely needs to have this feature.

**Comment by InnovateAsterisk** [comment]
The idea from the beginning was to keep this application similar to WhatsApp, in that you need to have a contact/buddy in order to communicate. At least a number. But I even find this an annoying feature of WhatsApp, so the idea is to make it faster and easier to get communicating, by allowing you to quickly make a very basic contact - say just the number - then build the details like name etc as you get more information. Its import that this contact creating stays in place, because the browser phone builds all sorts of data once the contact is created. The browser phone will never be some sort of "dialer", even if you are only going to call someone once, it has to make the contact - its just how the system works.

That being said... yes, quicker and easier is important too. I'll take a look at the keyboard entry options.

**Comment by edimondi** [comment]
hello, i was wondering for the moment if i can make like when i click the icon call to auto select invisible text field right above the keypad so i can start typing right away and just hit enter to dial, can you show me what i need to change to auto select the text field, is it easy to do it until you figure it out how to make keypad entry option. thanks

**Comment by edimondi** [comment]
Hi, i make it work to auto select text field and to dial when press enter. This is what i Changed on the phone.js
FROM **_var html = "<div><input id=dialText class=dialTextInput oninput=\"handleDialInput(this, event)\" style=\"width:160px; margin-top:15px\"></div>";_**	TO     **_var html = "<div><input id=dialText class=dialTextInput oninput=\"handleDialInput(this, event)\" onKeydown=\"pressEnter(event);\" style=\"width:160px; margin-top:15px\"></div>";_**  and under the **_dhtmlxPopup.show(x, y, w, h);	
}_** i added this: **_function pressEnter(e){
	if(event.keyCode === 13){
		DialByLine('audio');
	}
}_**

**Comment by acoolov** [comment]
Much better now Condrad!

**Comment by edimondi** [comment]
everything looks good now, thanks
