### ISSUE TITLE
Sending Registration... status stuck

### ISSUE THREAD

**Issue by edimondi** [InnovateAsterisk/Browser-Phone#146]
Hi, after i restart asterisk the phone get registered and works but on the status it says Sending Registration... here is what i have in the chrome inspect element:
**Fri Jul 09 2021 07:46:05 GMT+0000 (Greenwich Mean Time) | sip.transport | WebSocket disconnected (code: 1006)
Unregistered, bye!
Disconnected from Web Socket!
Fri Jul 09 2021 07:46:05 GMT+0000 (Greenwich Mean Time) | sip.transport | WebSocket abrupt disconnection
Web Socket error!
Fri Jul 09 2021 07:46:05 GMT+0000 (Greenwich Mean Time) | sip.transport | trying to reconnect to WebSocket wss://mydomain:8089/ws (reconnection attempt 1)
Fri Jul 09 2021 07:46:05 GMT+0000 (Greenwich Mean Time) | sip.transport | connecting to WebSocket wss://mydomain:8089/ws
WebSocket connection to 'wss://mydomain:8089/ws' failed: 
Fri Jul 09 2021 07:46:08 GMT+0000 (Greenwich Mean Time) | sip.transport | Transport error: [object Event]
Web Socket error!
Fri Jul 09 2021 07:46:08 GMT+0000 (Greenwich Mean Time) | sip.transport | WebSocket disconnected (code: 1006)
Disconnected from Web Socket!
Fri Jul 09 2021 07:46:08 GMT+0000 (Greenwich Mean Time) | sip.transport | WebSocket abrupt disconnection
Web Socket error!
Fri Jul 09 2021 07:46:08 GMT+0000 (Greenwich Mean Time) | sip.transport | Reconnection attempt 1 failed
Fri Jul 09 2021 07:46:08 GMT+0000 (Greenwich Mean Time) | sip.transport | trying to reconnect to WebSocket wss://mydomain:8089/ws (reconnection attempt 2)
Fri Jul 09 2021 07:46:23 GMT+0000 (Greenwich Mean Time) | sip.transport | connecting to WebSocket wss://mydomain:8089/ws
Connected to Web Socket!
Sending Registration...
Fri Jul 09 2021 07:46:23 GMT+0000 (Greenwich Mean Time) | sip.transport | WebSocket wss://mydomain:8089/ws connected**

**Comment by InnovateAsterisk** [comment]
Yes, the websocket connection will disconnect if Asterisk is restarted - this is the nature of stateful TCP connections. It is unfortunate, but as you can see in the log you show, the code attempts to re-connect, and from what i see the first attempt fails (probably because asterisk wasn't fully booted), but the next attempt connects. 

The next line should say "Registered!", but I don't see it, and suppose that this is why the UI isn't saying that the extension is registered.

I'm assuming that the registration completes correctly on a fresh load, and this only happens after an asterisk restart. I would take a look at the SIP trace in the Message Tab:

![image](https://user-images.githubusercontent.com/58937573/125049086-dfdb1c00-e0a0-11eb-9e01-ec234781692e.png)

**Comment by edimondi** [comment]
Yes this only happens when i restart asterisk and i can not find Message tab in chrome

**Comment by InnovateAsterisk** [comment]
I am able to re-create your issue, looking at a fix

**Comment by edimondi** [comment]
perfect, thank you very much ;)
