### ISSUE TITLE
Upgrade sip.js and Secure Authentication Data 

### ISSUE THREAD

**Issue by MarzieKeshavarz** [InnovateAsterisk/Browser-Phone#149]
Hello
I'm using this soft Phone and it's amazing. i want to upgrade to latest version of sip.js (0.20.0) but there is some issues ...
i have error in :
`var userAgent = new SIP.UA(options)`
and error is:
`sip.ua is not a constructor`
i searched about this and i find out there is some changes in new version (create userAgent moved to API module)
but i didn't understand how can i fix the error :((
is there any body that upgraded sipJs version?

**Comment by edimondi** [comment]
i tried and same issue with 0.20.0 so it works up to version sipjs 0.15.11. Here is a message that i got on version 0.15.11 **--- sip.ua | The UA class has been deprecated and will no longer be available starting with SIP.js release 0.16.0. The UA has been replaced by the UserAgent class. Please update accordingly.---**

**Comment by vaheed** [comment]
+1

**Comment by MarzieKeshavarz** [comment]
> 
> 
> i tried and same issue with 0.20.0 so it works up to version sipjs 0.15.11. Here is a message that i got on version 0.15.11 **--- sip.ua | The UA class has been deprecated and will no longer be available starting with SIP.js release 0.16.0. The UA has been replaced by the UserAgent class. Please update accordingly.---**

yes you're right i used `new SIP.UserAgent()`
but it's not the only problem... there is a lot of changes in new version like `userAgent.on("register") ` and etc ...
thank you for your answer :))

**Comment by InnovateAsterisk** [comment]
Phew... the ol elephant in the room... huh!
I looked at the newer versions, and there just so many breaking changes... I know i'll probably have to do it some day. Hang it there, i will!

Btw, is there any feature in particular that you guys need from the newer versions?

**Comment by MarzieKeshavarz** [comment]
I wanted to use Digest Authentication and i saw some new commits in latest versions
so i decided to upgrade my sip.js but i think i should forget it now :D

**Comment by InnovateAsterisk** [comment]
Not sure what you mean by Digest Authentication? The browser phone by default will attempt the REGISTER at startup, and auth is performed using the standard SIP Digest Authentication model using a hashed username, nonce and password, in response from the initial 401 response that your server should return. If your server is not responding with ```401 Unauthorized```, you must change your server settings,

**Comment by MarzieKeshavarz** [comment]
yes i know it ... i wanted to change authentication mode
because The user can see the username and password in source panel and it's not safe... so i wanted to add token to register method but I did not know if there was a parameter for it or not , 
Finally I found it with the `authenticationFactory` parameter in register method options... that use Digest Authentication by default but i can't change it (i didn't find sample code) and I still do not know if I can send a token ...

**Comment by InnovateAsterisk** [comment]
From their web site: "_Overriding the Authentication Factory is deprecated. We do not expect that this will work and will be removing it in a future version._"

With regards to sip username and password safety, I fully understand your concerns. From what I know there are only two other options, IP authentication, and to use pre-hashed passwords. Now since this is browsers based technology it's probably going to be impossible to use IP auth, since your clients could be all over the show. The pre-hashed passwords, although sound better in that they use an SHA hash and not plain text passwords, from what I understand security is actually lower because it would be subject to a replay attack. (The nonce doesn't change.)

If I was using this in a public and commercial context, I would keep the SIP Challenge method, but make the username and password completely arbitrary and temporary. It would require running asterisk with realtime DB. When the index (or whatever container) page loads, execute some backend code to enter the database, set a random key for username and password and return that same key pair to the settings for the browser phone. The phone would then register, using these details, that would only be valid for that session (because as soon as you reload the page, the details would have changed).

Something that would be a nice improvement to this project would probably be some sort of "provisioning" request, that could be set to send back SIP details.

**Comment by MarzieKeshavarz** [comment]
Thank you for your answer. 
I think the safest way is a one-time password.
Of course, it can not be ignored that this password can be used during the lifetime of the session.
We left the main topic of issue because I am editing the issue title

**Comment by InnovateAsterisk** [comment]
Yes, after the initial REGISTER, subsequent INVITEs will require auth too. One thing to consider, is that if you remove all other transport options, and leave only the wss transport via TLS, you have a level of security in that only browser based connections could connect and possibly use the (now valid) SIP credentials, that are only made available because another user would be using them. You can also have some sort of session timeout, that expires the credentials.

It's not perfect, but it's a start.

**Comment by InnovateAsterisk** [comment]
It's now on version 0.20.0
