### ISSUE TITLE
Licensing conflict

### ISSUE THREAD

**Issue by gerhardt-bergmann** [InnovateAsterisk/Browser-Phone#152]
Are you aware of the licensing conflict between the GPL v2.0 of the `dhtmlx` library used extensively by Browser Phone and the LGPL v3.0 under which you distribute your project ?

Both files: `dhtmlx.js` and `dhtmlx.css` included in Browser Phone either as off-line dependencies or as library files downloadable at run time are part of the dhtmlxSuite v.5.1.0 Standard edition licensed under GPL v2.0 only, the copyright belonging to UAB Dinamenta (http://www.dhtmlx.com). 

As you can see on the official Free Software Foundation's website [here](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility), you cannot include code licensed under the GPL v2.0 into a LGPL v3.0 application.

If the `dhtmlx` library had been licensed by using the terms 'GPL v2.0 or (at your option) **any later version**', you could have 
included it in a LGPL v3.0 application, but the combination would have had to be published under the GPL v3.0, as shown in the compatibility matrix mentioned above. The consequences of the words **any later version** are specified in article 9 of the GPL v2.0 [here](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html ). However, the copyright notice of the `dhtmlx` library doesn't contain the words **any later version** neither in version 5.1.0 or in the [latest version of the dhtmlxSuite Standard edition](https://github.com/DHTMLX/dhtmlx-suite-gpl), which is 6.1.4. Even more: on the official dhtmlx forum, a representative of the development team mentiones explicitly in [this post](https://forum.dhtmlx.com/t/is-dhtmlxgantt-gplv2-or-gplv2-or-later/32778) that they released the dhtmlxSuite Standard edition under GPL v2.0 only and not under GPL v2.0 or "any later version"; at least from version [4.5.1](https://github.com/DHTMLX/dhtmlx-suite-gpl/tree/5.x) onwards. On [this forum post](https://forum.dhtmlx.com/t/gplv3-agpl-compatibility/33759) they even refuse to change the GPL v2.0 only license to other newer GPL version.

They also stress that you can only include the `dhtmlx` library in GPL v2.0 applications in [this forum post](https://forum.dhtmlx.com/t/standard-license-distribution-right/21297). 

The fact that the `dhtmlx` library can be downloaded at run time from a third party doesn't influence the licensing obligations. The `dhtmlx` library is too deeply integrated with Browser Phone to be considered a separate program. Browser Phone makes extensive use of the library and is so strongly connected to it that all the windows, pop-ups and menus cannot function without it. The term 'dhtmlx', either as an instantiation of the `dhtmlXWindows` or the `dhtmlXPopup` class, appears 87 times in the `phone.js` file. Therefore, Browser Phone and the `dhtmlx` library cannot be considered two separate programs that would constitute a software aggregate, in which the license of one component can be different from that of the other component. They can only be regarded as a combined work, and as the text of the [GPL v2.0](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html) (article 2 point b) specifies, any 'derived' program, or program that contains a GPL v2.0 licensed program, has to be licensed as a whole under the GPL v2.0.

The only solutions to this licensing conflict is to either change the license of Browser Phone to GPL v2.0, or to keep the LGPL v3.0 license for Browser Phone, but completely remove the `dhtmlx` library, replacing it with a library under a more permissive license.

If you change the license for the entire project to GPL v2.0, you can consider including the words 'or (at your option) "any later version"', in the copyright notice included in a central license file, or at the top of the Browser Phone files. If you do so, any program derived from Browser Phone can adopt a GPL version more recent than GPL v2.0, although this would require to remove the `dhtmlx` library from the project. If you don't include "any later version" in the copyright notice, all the derived programs will have to be released as a whole under GPL v2.0.

If you remove the `dhtmlx` library completely from your project, maybe replacing it with a similar library under a more permissive license, like the MIT licensed [Umbrella JS](https://github.com/franciscop/umbrella) library, you can keep the LGPL v3.0 license for the whole project, or you can choose a different FOSS license.

Please, consider solving this licensing conflict because in the current form, Browser Phone can give rise to legal disputes for you and for anyone who intends to use this software.

**Comment by InnovateAsterisk** [comment]
Hi Gerhardt, thank you for brining this to my attention. I was not aware of this conflict, and do apologise for this misunderstanding. I assume you work for DHTMLX legal department, so I assure you I will consider my options over the next few days and, from what I understand, either remove the DHTMLX references or change the license to GPL v2.0.

**Comment by lucas-oliver-trondsen** [comment]
Hi,
You can replace the `dhtmlx` library with the [Jeegoopopup](https://github.com/tweego/jeegoopopup/tree/1.0.0) library. It is similar but more light-weight. It allows setting pop-up dimensions, pop-up position, overlay opacity, etc.. It has been developed a while ago but it works perfectly with jquery v3.3.1. It's MIT licensed.

With the exception of the `dhtmlx` library, all the other JavaScript dependencies of Browser Phone are MIT licensed, so, if you manage to replace `dhtmlx` with Jeegoopopup, you can license the whole project under the MIT license. This would allow integrating Browser Phone, or parts of it,  in free and open source applications and also in proprietary applications. If on the contrary, you want to enforce the 4 freedoms of free software upon all the programs derived from Browser Phone, so that no proprietary program could integrate Broser Phone, the best license for this is the Affero General Public License v3.0, because it allows integrating an AGPL program only in programs with a similar license that guarantee the 4 freedoms, and in addition to this, if a company uses Browser Phone either in modified or unmodified form, to sell online services, they are forced to publish the software used to provide those services, so that all the modifications and improvements made to Browser Phone are returned to you and the community.

I don't think the LGPL license is suitable for this type of project. The LGPL was conceived by Richard Stallman as a sort of compromise, to allow proprietary programs to use GPL licensed, external libraries. By using LGPL licensed external libraries, the proprietary programs were not forced to become GPL programs. But Browser Phone cannot be considered an external library. It's a program in itself.

**Comment by edimondi** [comment]
what if you make keypad static without pop up, in my opinion it is better because its always there when you need it and its one click less if you try to dial.

**Comment by lucas-oliver-trondsen** [comment]
@edimondi Even if the keypad is made static, as you suggest, the licensing conflict is still there. The `dhtmlx` library is used in Browser Phone not only for the main keypad and the 'active line' keypad, but also for the user menu, for the 'add contact' and 'edit contact' windows, for the connection configuration window, for the mini-menus that appear when hovering over the phone icons, and in other places, offering different functionalities. If the `dhtmlx` library is kept as part of Browser Phone, the GPL v2.0 of `dhtmlx` requires that the author releases the whole application under the GPL v2.0. What I was suggesting above was to remove the `dhtmlx` entirely from the project and replace it with the [Jeegoopopup](https://github.com/tweego/jeegoopopup/tree/1.0.0) library (documentation [here](http://www.net-developer.nl/en/jeegoopopup/documentation/v100#properties)).

Unlike `dhtmlx`, Jeegoopopup is MIT licensed and this offers this project the chance to be licensed under any license, including the MIT license or the AGPL v3.0, as I suggested above.

After the licensing issue will be solved, the author can consider making the main keypad always visible, but this means that it will take a lot of screen space in all situations, including on mobile screens. I think the best approach would be to include a checkbox somewhere in the settings, to be able to make the keypad always visible or to leave it as a popup that appears when you click on an icon.

**Comment by InnovateAsterisk** [comment]
Thank you for everyones input on this. I believe that the best approach will be to remove the dhtmlx library from the project, and re-code the sections that use the library. There are a number of reason for this, and it will take longer to do so, but the end results will be better, especially for touch friendliness. I cannot commit all of my time to this project, but will endeavour to make these changes over the next few weeks, and can assure all parties that the very next release will not include the dhtmlx library. I trust this will suitable for all parties.

**Comment by lucas-oliver-trondsen** [comment]
@InnovateAsterisk  Will you consider licensing Browser Phone as MIT or AGPL v3.0 ?

**Comment by InnovateAsterisk** [comment]
I'm not really a lawyer, but from my understanding the MIT license is really a free-for-all license, and the AGPLv3 is almost exactly the same as the GPLv3... so for the moment ill leave it as is.

I have removed the dhtmlx library so long, and am working around the various UI changes. Progress so far:
 
![image](https://user-images.githubusercontent.com/58937573/128387265-e95091bd-1818-453d-8a31-622ee4f3f8de.png)

![image](https://user-images.githubusercontent.com/58937573/128387311-37451d0f-14f2-47ed-bd2d-6f8990b104e2.png)

**Comment by lucas-oliver-trondsen** [comment]
@InnovateAsterisk  Thank you for your reply. The new changes that you listed above look very good.

The MIT license is used by developers to give others the chance to include their code into any type of project, be it 'free and open source software' or 'proprietary software'. However, the original copyright notice and the specific permissions have to be included in all derived works. The MIT license gives developers the chance to license the derived works under a MIT license, but also under GPL, AGPL, LGPL, or a proprietary software license. Since you didn't choose GPL or AGPL for Browser Phone when you first published it, but LGPL, I assume your intent was to give other developers the chance to include your code into LGPL / GPL licensed projects, but also into proprietary software, since unlike other GPL licenses, the LGPL gives developers the right to use a LGPLed library as a dependency of a proprietary program.

The AGPL, on the other hand, is a license designed to enforce the 4 freedoms (to use the code as you wish, to modify the code, to distribute unmodified versions of the code and to distribute modified versions of the code) upon all derived works. Indeed, it's very similar to GPL, but it has an important addition: when a developer or a company uses AGPLed code to offer online services, for example Skype-like services, they are obligated to publish the code used to offer those services. This ensures that any modifications made to the original code are not kept secret and used selfishly, but they are published and in this way returned to the original author who did most of the work. This provision is not included in any versions of the GPL or LGPL. It's only in AGPL. In fact the AGPL was specifically designed to remove the loophole of offering online services with modified GPLed code that is kept secret because it is not distributed. So, if you publish Browser Phone under LGPL, any company can take it, extend it, then use it to sell online Skype-like services, without releasing the source code, since they don't distribute the program: they just use the program to offer those online services. The LGPL allows such behavior, while the AGPL doesn't allow it. This selfish behavior is not only possible, but it has already happened, as some FOSS developers complained.

The best license would be AGPL v3.0, but if you publish Browser Phone under the MIT license, at least you will give other developers the chance to include it in AGPL v3 projects. On the other hand, if you license it under the LGPL, all the derived works will have to be licensed under the LGPL or GPL and not AGPL, so the loophole mentioned above will remain open and as I mentioned, any developers or companies will be able to take Browser Phone, modify it, then use it to sell online services, without publishing the modified code, since the  LGPL allows them to do so.

**Comment by lucas-oliver-trondsen** [comment]
@InnovateAsterisk  Please tell us if you will maintain the LGPL v3.0 license for Browser Phone. Thank you.

**Comment by InnovateAsterisk** [comment]
I have not decided yet, but am comparing the different options. I see though that the AGPLv3 may be a better option.

**Comment by lucas-oliver-trondsen** [comment]
@InnovateAsterisk  I managed to completely replace the `dhtmlx` library with the MIT licensed [Jeegoopopup](https://github.com/tweego/jeegoopopup/tree/1.0.0) library mentioned above. The popups look very similar with the `dhtmlx` popups. Will you accept a pull request if I make one against the current version of Browser Phone ?

**Comment by InnovateAsterisk** [comment]
With this license conflict, it forced me to do something that I wanted to do anyway - the dhtmlx library was way too big for the simple functions that I ended up using it for: Windows, Popup Menus, Tabs.

My objective is now to remove the need for the UI tools in the first place - Windows, and Popups are not very **Touch Friendly**, and don't scale down to smaller screens well... so I actually want to take them out anyway.

However, I will leave components for backward compatibility:
For Windows, I have used the jQuery UI system, that was already partially implemented (with jQuery). jQuery is heavily used in this project, so it makes sense to use jQuery UI to make a simple Window - the replacement code was extended out to OpenWindow(), Alert(), Confirm(), and Prompt(), so customisations can continue without change. 

Next was Tabs, only used in the Edit Settings Window, well, that has been changed conceptually, and taken out - unfortunately jQuery UI only has a very rudimentary Tabs system - sorry for this limitation.

Finally... Popups - as you know from this project, the popup system came into some critical points of the project, like the dial button, and the main system menu... however, again, I will probably use a form of the jQuery UI library to implement the same functions - but also, design the requirement out completely, and only leave something for backward compatibility.

So to answer your question, I really appreciate your input on this and although it may take a little longer, I will probably not use the Jeegoopopup, and continue to design out the use of popups entirely.

**Comment by InnovateAsterisk** [comment]
The new settings page, and button.
![image](https://user-images.githubusercontent.com/58937573/129478089-b0c63ef7-613c-4406-988c-0dc9b631c7e4.png)

**Comment by lucas-oliver-trondsen** [comment]
The changes that you listed above look very well. Also, the jQuery UI library seems to be MIT licensed and smaller than the `dhtmlx` library, so it seems a good choice. It may be even better than Jeegoopopup. In my version, I will keep the Jeegoopopup library though, since I worked so much to implement it and it looks very good too.

However, the current Browser Phone repository still contains the Browser Phone version dependent upon the `dhtmlx` library which creates the licensing conflict mentioned above. Do you intend to upload the new Browser Phone version, even if incomplete, but without the `dhtmlx` library, and with a license of your choice, be it LGPL or AGPL or other FOSS license, so that the licensing conflict can be solved ?

**Comment by InnovateAsterisk** [comment]
I should be able to release a working version in a week. I would rather not release broken code.
