### ISSUE TITLE
download recording

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#28]
Is it possible for the user to download a call recording? The feature is really useful and elegantly displayed, but the user would rather save a copy in a server's directory (with backup support) instead of the browser's cache (which can easily be erased for many reasons).
Minor issue but useful.

**Comment by InnovateAsterisk** [comment]
Well, the idea is that it is already saved on your PC, so it may seem redundant, but you have a point about remote backups or administrative review. 

So when making this, I had this idea that people could enhance this app, by using a plugin or a CallRecordings_post.js (web worker) that would in its own thread: 
1, collect all the call recordings according to some filter, say date
2, upload them to say AWS, dropbox, Google, network SAN
3, Delete them form the local store after a specified time. (free up user space)
(4,) An improvement I could implement is that there could be a flag in the CDR's that would mark the call recording as "uploaded", and provide the user with a link rather than the actual Blob data, clicking that would initiate a download.

The same sort of thing could be applied to the actual CDRs, i'm not sure if you noticed that there is a lot of extra data saved to the CDR, and more to come too. This data could have value, like quality analysis, or even behaviour analysis (like transfers, conference calls during calls). The CDRs too could be collected, saved to the cloud, and trimmed.

P.S. The native HTML5 download option of a call recording does appear, but only shows once the audio or video file has played. This is because it attaches an in-memory stream to the Blob data in storage - of course method this is only useful of occasional use.

**Comment by InnovateAsterisk** [comment]
There is a link now in the new call details window. You can either click the “save as” link or right click, and use your browser save link as feature. The term save as is more accurate as the recoding is already locally saved to your pc.

**Comment by vieridipaola** [comment]
Great, thanks!
