### ISSUE TITLE
BrowserPhone  Chat server configuration

### ISSUE THREAD

**Issue by mayankmaheshwari** [InnovateAsterisk/Browser-Phone#304]
How to configure Browser phone to use XMPP as chat server instead of SIP. In account settings I have configured all the XMPP related para meters however, BrowserPhone continue to use SIP for chat messages.
My XPPP server is openfire.

**Comment by InnovateAsterisk** [comment]
Firstly, its quite limited - and the fire transfer doesn't work yet, but the basics are as follows.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/58937573/183029016-36efb3d6-1046-4e31-a978-bffec6a81206.png">

Set your chat engine to XMPP, and complete the field details similar to above. Note that in my configuration my domain setting matches that of the domain setting in open fire.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/58937573/183029526-a9451f49-3b33-4088-a74b-aa0547a49d99.png">

Also note that users are not automatically populated in OpenFire, it's something that you need to do each time you add a user to Asterisk.

When you make a user on OpenFire, just add the user like this:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/58937573/183031004-fc318804-1ce1-4fe3-8aee-f1c0c59202e7.png">

There is nothing else needed to create the user - but the Username must be the same as the DID for the Asterisk User (Not sip username), and the password must be the sip password. So a typical setup may be:

**Asterisk SIP:**
Name: Conrad
DID/Extension: 100
SIP Username: User1
SIP Password: 1234

**OpenFire XMPP:** 
Username: 100 (same as sip DID/Extension)
Password: 1234 (same as sip password)

At this point, when you open the Browser Phone, and the system registers the user on Asterisk, it automatically registers the xmpp session on OpenFire. so you will get this:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/58937573/183035800-28358e12-5c91-458f-86ae-85913aefa467.png">

At this point you can do things like set your Profile picture, and it will automatically distribute to all your buddies. Same with personal information, like email etc. (In Appearance Tab)

You can also set your status. Next to your name (top left), click the settings menu, and at the bottom - set status. 

These are all function of XMPP, but don't involve any buddies.

Now that this is done, you can add Buddies. If you have already made a buddy as "Basic Extension" you cannot convert it over to XMPP. You need to delete and re-create.

But making a new buddy is easier - all you need is the DID/Extension of the other asterisk User. So if you are 100 on Asterisk and your buddy is 200, just enter 200.

<img width="316" alt="image" src="https://user-images.githubusercontent.com/58937573/183036660-f6493598-7bff-4320-a30e-16ee7c5ed244.png">

Once the new buddy is there, messages should be sent as XMPP. Just be sure that the user adds you as a buddy on their side, so that you can chat.

**Comment by mayankmaheshwari** [comment]
Thanks a lot Conrad for a very quick reply. I was using sip user name in openfire instead of DID.
