### ISSUE TITLE
proper unregister and hints/presence

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#344]
Hi,

I don't know if this is more of a question I should ask on the Asterisk ML, XMPP ML (Prosody in my case) or here.

Presence is working fine in Browser-Phone for both XMPP and SIP extensions.

There's only one case where the presence state is not properly updated -- when the browser-phone client suddenly vanishes (ie. the client browser closes for whatever reason).
The user is not unregistered properly, and the presence status remains the same (to others, of course) as it was before the client "died".
If the status was "online" it will remain so for subscribed users even if it actually isn't.

Is there a workaround or fix for this?
I guess it's more server-side than client-side, right?

Regards

**Comment by InnovateAsterisk** [comment]
I think the problem here is that the onbeforeunload only really allows you to issue a short amount of code, and as soon as the thread is done, it will close the session. This means anything that is async, or even on a settimeout, will not be executed. The code deregisters the sip account, but then gives up on just about anything else, leaving the browser to dump the web-socket connection(s). I am not even sure if it tries to de-register the XMPP account. 

I can take a look at this.

**Comment by InnovateAsterisk** [comment]
I have included this:

```
$(window).on("beforeunload", function() {
    Unregister(true);
    if(XMPP) XMPP.disconnect("");
});
```

**Comment by InnovateAsterisk** [comment]
http://strophe.im/strophejs/doc/1.2.6/files/strophe-js.html#Strophe.Connection.disconnect

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/36751ca929ba884ce57c19077d6ac6680adf14d4
