### ISSUE TITLE
XmppDomain

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#350]
Hi,

XmppDomain has been deleted in the new release.
Why?
I need to use a different domain than SipDomain for XMPP.

Can the variable be restored?
If the user does not define it then XmppDomain = SipDomain.

Thanks

**Comment by InnovateAsterisk** [comment]
Well, SipDomain didn't exist before, so SipDomain was introduced, and is used for both a new global SipDomain option and XMPP. (It was actually going to be called just Domain, but i found it more useful as a Sip setting and share it with the XMPP settings.) If your XMPP domain was xyz.com use this in the SipDomain so that it can be used for both settings.

**Comment by vieridipaola** [comment]
It's a bit confusing because phone.js then uses this kind of construct in several places:

`SIP.UserAgent.makeURI("sip:" + SipUsername + "@" + SipDomain);`

In any case, I set _SipDomain = "xmpp.mydomain.org"_, and everything seems to be working as expected.
