### ISSUE TITLE
beforeunload event: ask for user confirmation

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#381]
Hi,

Would it be possible to ask for user confirmation before closing browser window?
Or deny closure until user in Browser Phone page has explicitly unregistered (eg. by pressing an Unregister/Close/Whatever button)...

**Comment by InnovateAsterisk** [comment]
So there is a bit of a problem with implementing this... let's say its a choice. 

When ```onbeforeunload``` is called, its a bit of a "last-ditch" effort, and on top of that, there are various browser behaviours that my or may not be stable or consistent in their behaviour. https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

The problem lies in the timeline of things, if you are going to stop the execution, say with a non-null return, you will essentially ```return``` the script, and ask the user the question. The problem is that if the user answer is "Cancel" (remain on the site), no code can be executed (because of the return), and because you didn't know before hand what the intention is going to be, you cant execute any further unload script, like unregister, etc.

You following the problem? If you ask the unload question, you can't act on the response (like to unregister). If you preemptively unload everything and then ask the unload question... again you cannot act on the response (like to re-register). 

It's pretty much only works if the response to the unload question is Cancel since then nothing was actually done and no harm was done. (except the developer tools are unloaded ;( )

I found it was more useful to correctly unregister the account, than to try prevent the user. And to redraw the UI exactly as it was when they left, to give as seamless an experience as possible.

Also another situation exists, because the choice is "continue" or "don't continue", what about the 3rd choice most people forget... "Do nothing". In this case, javascript is paused, and slowly your phone deregisters, and probably will even disconnect its websocket connection due to inactivity... leaving you with even more mess to deal with.

You will probably find the best option is to check if there are any calls in place, and only if there is actually an active call - then return the unloadscript, knowing that the user is in a call, and that we assume is they would want to Cancel the Unload to remain in the call! Know though that if the user clicks Reload, then none of the rest of the unload scripts can fire (remember the cart-and-horse situation) it would be to late. In all honesty though if you are on a call, and you hit reload... all of your media streams just become dead, and there is quite a lot of mopping up Asterisk has to do... the unregister will be the last of the problems. Technically this is the same as someone yanking the power cable out of the phone.

I have implemented the call check return for the next release.

**Comment by vieridipaola** [comment]
I had a gut feeling it would be complicated.
It just so happens that some desktop users inadvertently close the Browser Phone window as it appears just like any other browser window. Then they realize they're not receiving any calls because their webrtc client isn't open anymore...
 
Maybe another approach to mitigate my problem is to use PWA even on desktops like I suggested in another "issue" I posted. The advantage of using Browser Phone as a PWA even on desktop is that the user sees it as a different app thus potentially avoiding unwanted closures.
I know I can manually configure Browser Phone as a PWA on desktop, but if I have the time I can test a proposal for a minimal setup for PWA so that any user who opens the Browser Phone site for the first time can press the + icon to save the PWA.
Hopefully they will then only use that instead of the browser.

I know Firefox doesn't support PWA on desktop natively (really too bad), but Chrome and any other based on it (like Edge) do.

**Comment by InnovateAsterisk** [comment]
Try version 0.3.19

**Comment by InnovateAsterisk** [comment]
> Maybe another approach to mitigate my problem is to use PWA even on desktops like I suggested in another "issue" I posted. The advantage of using Browser Phone as a PWA even on desktop is that the user sees it as a different app thus potentially avoiding unwanted closures.
I know I can manually configure Browser Phone as a PWA on desktop, but if I have the time I can test a proposal for a minimal setup for PWA so that any user who opens the Browser Phone site for the first time can press the + icon to save the PWA.
Hopefully they will then only use that instead of the browser.

Probably the best approach on this would be to use Electron to create a container application. This is exactly what WatsApp desktop is.( You can even use [option] + [command] + i on a mac to open their developer tools!! lol )

Any way... the point is the mandate behind a PWA is heave use of Service Workers, and predominately able to work offline - so unfortunately these checkboxes cannot be checked, but (like WhatsApp) deploying the Browser Phone as an Electron Application means that you are in control of the close button.

**Comment by vieridipaola** [comment]
I'll try 0.3.19.

I haven't used Electron yet.
Would it be something like this:
https://jordan-eckowitz.medium.com/make-any-website-into-a-desktop-app-with-1-line-of-code-ba53d59bf9e1
I remember trying out nativefier once a few years ago, but not for Browser Phone.
I'll try that out too.

Thanks

**Comment by InnovateAsterisk** [comment]
It’s probably a little more than one line 🤣, but yea, that’s it. I have tested the browser phone, and it seems all to work fine. 

The git project isnt release based, so it can’t update by itself, but I figured that’s more something you guys should all be doing in any case.

**Comment by vieridipaola** [comment]
I tried 0.3.19, but despite having one active call the Firefox browser window immediately closed when I pressed the tab's cross.
The call on the other end was still live until Asterisk cleaned it up.

**Comment by InnovateAsterisk** [comment]
Fixed, in the next release

**Comment by InnovateAsterisk** [comment]
Tested in Firefox 107.0 (64-bit) on Mac. Works as expected.

**Comment by vieridipaola** [comment]
Yes, works fine now!
Thanks!
