### ISSUE TITLE
Saving and retrieving credentials at each browser phone start

### ISSUE THREAD

**Issue by field64** [InnovateAsterisk/Browser-Phone#471]
### Discussed in https://github.com/InnovateAsterisk/Browser-Phone/discussions/469

<div type='discussions-op-text'>

<sup>Originally posted by **field64** September 23, 2023</sup>
Apologies if this is an inappropriate question.

Browser-phone is an excellent piece of work, thank you. Would be a joy if some of the alleged professional software developers i work with daily would strive for even a shred of the intelligence and quality on display here.

I'm not much of a coder, so perhaps I am way off base, but am running the browser-phone on a number of devices, each with it's own pjsip credentials, but when the device clears it's browser cache, the next start of the phone requires the user enter all credentials again.

I read  #216 - https://github.com/InnovateAsterisk/Browser-Phone/issues/216, and found the credentials on one case are stored here:

~/.config/BraveSoftware/Brave-Browser/Default/Local\ Storage/leveldb/009396.ldb 

Is there a preferred method for each device to save successful credentials and have the client device browser associate that file with the application and authenticate ?  Ideally an encrypted file in $HOME,  so the browser page would prompt to enter a passphrase to decrypt the file (user proves at least something) , send the credentials into the browser page and log the user in ?

Thank you for a hint in the right direction.

</div>

**Comment by InnovateAsterisk** [comment]
So the Browser Phone solution you find here is more of a proof of concept than a final product. The index.html page is a simple static page, so sure if you consider using it in your own work, you would need to add functionality to enable the features you need. It seems like you want to have a more Whatsapp or Telegram like experience. This is all possible, but will require your development to get it there, mainly because the way everyones backend systems work is completely different.

**Comment by field64** [comment]
Thanks for the information, this was what i was thinking.
