### ISSUE TITLE
CID in the incoming call information

### ISSUE THREAD

**Issue by ogogon** [InnovateAsterisk/Browser-Phone#68]
Having received an incoming call, the program displays information about who made it.
Sometimes she creates a separate window, and sometimes she writes at the top of the already existing right one. Until I figured out why two different ways are used.

However, in both cases, only the text part of the SIP CallerID is displayed. The digital number is not displayed.
I believe that this greatly reduces the information content of the notification.

In my opinion, in a separate window, the digital number should be displayed under the text, in a separate line with a slightly smaller font. And in case of notification in the upper part of the right window - in brackets, behind the text. In both cases, there is room, and this should not limit anyone.

**Comment by InnovateAsterisk** [comment]
The difference is if you have the selected user/buddy already highlighted. 

If you select Buddy-A (on the left) and Buddy-A calls you, there is no need to throw open a window, or use the Notify system, however if you have another buddy selected (maybe you are sending a text message etc), then the popup window will notify you of an incoming call. The popup has a few choices, and importantly "close" without taking any action... in other words "carry on ringing", then you can finish up with selected buddy, and change over Buddy-A, and answer the call when you are ready.

I can include the numerical number in the popup. However when a call comes in via a trunk or cellular network its will probably just be a repeat of the caller ID, something like "+12345678901" <+12345678901> because most non-voip networks don't support text in the callerid. 
I'll look at that.

**Comment by vieridipaola** [comment]
Good idea. If it's a repeat (callerIDname == callerIDnum) then only print callerIDname, I guess.

**Comment by InnovateAsterisk** [comment]
Done
