### ISSUE TITLE
web hook on outbond call authentication error

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#97]
Hi,

I came across a scenario where if for some reason one reloads the pjsip module after an endpoint's password change, but the webrtc client was online and "registered" during this change, the Browser-Phone displays the local status as "registered" but any attempt to make a call fails with a transient messgae saying that authentication has failed. The end user doesn't really know what that means or implies so he/she will not think of "refreshing the registration" (also because it states to be  properly "registered" already).

I'm not sure what to do to avoid these special cases and somehow force the client to re-register. I'm not too familiar with pjsip so I don't know if there's a registration timeout we could honor. It's not clear to me if the qualify* options are for this or just for presence. 

Maybe one simple way would be to catch the authentication error when the client tries to make a call and then force a re-registration or run a web hook function so one can decide to re-register or not.
Of course, this would not solve the problem for incoming calls that will not go through because the client is actually not registered (until there's a timeout I suppose), but at least things will get fixed as soon as the user tries to make a call (or a suibsequent one).

**Comment by InnovateAsterisk** [comment]
In my experience with SIP, this is on of the more annoying ones. In the past I have include various tools like API calls to check the server status (rather than asking the phone), and performing re-registers based on that response. Having the server and the phone agree to the state of registration isn't always 100% achievable, and it's just because of the nature of the technology. 

If bandwidth isn't too much of an issue... making the phone register more often closes this gap between changes made server side, and the device registering. I think the default registration expire is 300seconds (always set this on the phone, not Asterisk), try bring it down to 120sec or even 60. This would largely be determined by how many end users you anticipate.

**Comment by vieridipaola** [comment]
Through the use of "RegisterExpires" in Browser-Phone, for instance, which sets registerExpires in SIPJS.

I guess I could also check the status in the web hook "on_terminate", and if I see that it's an auth issue then I can inform the user to reload the page so the client can re-register properly.

Thanks
